# Generated by Django 3.2.19 on 2023-06-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_user_name_todosign_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='usertask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.CharField(default='', max_length=200)),
                ('percentages', models.CharField(default='', max_length=200)),
                ('dates', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
