# Generated by Django 3.2.19 on 2023-06-06 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_usertask'),
    ]

    operations = [
        migrations.AddField(
            model_name='todosign',
            name='image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
