# Generated by Django 3.2.19 on 2023-06-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_todosign_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todosign',
            name='image',
        ),
        migrations.AddField(
            model_name='usertask',
            name='userimage',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
