# Generated by Django 3.2.19 on 2023-06-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20230606_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='userimage',
        ),
        migrations.AddField(
            model_name='todosign',
            name='userimage',
            field=models.ImageField(blank=True, upload_to='userimage'),
        ),
    ]
